### ISSUE TITLE
SIGSEGV while debugging program

### ISSUE THREAD

**Issue by jkralik** [pgermishuys/goes#11]
While i debugging i get message about reconnect and after that i get SIGSEGV

The problem is that `connection.socket` is set to nil during write. From my pointview - closing socket cannot set `connection.socket` to nil.

LOG:
`
2018/09/13 11:30:11 [info] connection (id: b775ac4d-13da-470e-9e86-c3a46cd07a7f) reconnected
2018/09/13 11:30:14 [info] closing the connection (id: b775ac4d-13da-470e-9e86-c3a46cd07a7f) to event store...
'
2018/09/13 11:30:14 [error] connection (id: b775ac4d-13da-470e-9e86-c3a46cd07a7f) closed
2018/09/13 11:30:14 [info] connecting (id: b775ac4d-13da-470e-9e86-c3a46cd07a7f) to event store...
2018/09/13 11:30:16 [info] successfully connected to event store on 127.0.0.1:1113 (id: b775ac4d-13da-470e-9e86-c3a46cd07a7f)
2018/09/13 11:30:16 [info] connection (id: b775ac4d-13da-470e-9e86-c3a46cd07a7f) reconnected
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x863ac6]
goroutine 57 [running]:
github.com/pgermishuys/goes/eventstore.(*TCPPackage).write(0xc4201e7768, 0xc4200c6500, 0x0, 0x0)
	/home/krz/gocode/src/github.com/pgermishuys/goes/eventstore/tcppackage.go:86 +0x466
github.com/pgermishuys/goes/eventstore.sendPackage(0x200000000, 0xc420204290, 0x10, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/krz/gocode/src/github.com/pgermishuys/goes/eventstore/connection.go:232 +0xf3
created by github.com/pgermishuys/goes/eventstore.readFromSocket
	/home/krz/gocode/src/github.com/pgermishuys/goes/eventstore/connection.go:201 +0xb6b
`

**Comment by pgermishuys** [comment]
@jkralik are you still using this client? if so, in what capacity?

**Comment by jkralik** [comment]
Hi. No we are not using it. We implemeted our cqrs library https://github.com/go-ocf/cqrs
